"""
Production adapter over Phase 2's recovery propensity model.

CORRECTED per a Phase 5 re-audit (see gaps.md §C.2 for the full writeup):
this now loads the CALIBRATED LOGISTIC REGRESSION model (model_lr.pkl +
feature_transformer_v1.pkl), NOT the LightGBM booster the original Phase 2
certificate named as "primary". Re-deriving the numbers directly from the
parquet files (not trusting the certificate's summary) found that
`val_random` -- the split models/recovery/train.py used to pick the "best
model" and compute the certified LR-vs-LightGBM AUC gap -- is 58.8%
byte-identical duplicate rows of `train` (both generated by independently
re-seeding the same seed=42 RNG from index 0, so the first N episodes of
any two same-seed calls replay identically). LightGBM's reported AUC
advantage on that split was a memorization artifact, not generalization.

The ONLY split with verified zero overlap with train is `test_temporal`
(seed=999, confirmed by direct episode_id set comparison). On that split,
from models/recovery/artifacts/eval_test_temporal.json:
    LightGBM AUC = 0.8374  (95% CI: [0.8277, 0.8471])
    LR      AUC = 0.8378
LR is marginally HIGHER, and LightGBM's point estimate sits inside its own
CI around LR's number -- they are statistically indistinguishable, and
LightGBM does NOT clear TRD §3.3's own >0.03-AUC-lift gate on genuinely
held-out data. Per that same TRD rule ("ship logistic regression first,
gate the upgrade behind a real improvement check"), the gate fails and LR
remains the default. This is not a new training run -- both artifacts
already existed from Phase 2; this file simply points at the one the real,
uncontaminated evidence actually supports.

This is still NOT a new training pipeline: no fitting happens here, ever.
The FeatureTransformer (feature_transformer_v1.pkl) was fit on train only
and is loaded frozen; the LogisticRegression (Platt-calibrated via
CalibratedClassifierCV) is loaded frozen. Retraining or re-fitting either
at runtime would defeat the entire point of "certified, frozen artifact."

FEATURE SCHEMA (frozen, Phase 2's training schema, models/recovery/features.py):
    Categorical (one-hot): method, bank, initial_failure_class,
        initial_failure_code, merchant_id
    Continuous (log1p + standardize): amount_paise
    Cyclic (sin/cos): hour_of_day, day_of_week
    Passthrough: is_returning_customer, customer_ltv_decile

KNOWN LIMITATION — read before deploying to a real merchant: `merchant_id`
was one-hot-encoded against exactly 3 synthetic merchant UUIDs seen during
training (OneHotEncoder(handle_unknown="ignore") in features.py). ANY real
production merchant_id is an unseen category -- OneHotEncoder handles this
gracefully (all-zero indicator row, does not error) but it means
merchant_id contributes ZERO signal for any actual merchant in production.
Same underlying gap the LightGBM path had; not fixable without retraining
on a broader merchant population.

Model load-once discipline: both the transformer and the LR model are
loaded from disk exactly once per process (module-level singletons, double-
checked locking), never re-read or re-fit per predict_recovery_probability()
call.
"""

from __future__ import annotations

import math
import pickle
import threading
from dataclasses import dataclass
from datetime import datetime
from pathlib import Path

import numpy as np
import pandas as pd

from simulator.episodes.generator import _compute_ltv_decile

_ARTIFACTS_DIR = Path(__file__).resolve().parent.parent.parent / "models" / "recovery" / "artifacts"
MODEL_ARTIFACT_PATH = _ARTIFACTS_DIR / "model_lr.pkl"
TRANSFORMER_ARTIFACT_PATH = _ARTIFACTS_DIR / "feature_transformer_v1.pkl"

# Ties every candidate_actions/diagnoses row back to the exact certified
# artifact — model lineage chain: decision -> model_version -> this
# correction's evidence (eval_test_temporal.json) -> feature_schema_version.
MODEL_NAME = "recovery_propensity_logistic_regression"
MODEL_VERSION = "phase2-certified-lr-v2-corrected"
FEATURE_SCHEMA_VERSION = "phase2-v1"

CATEGORICAL_FEATURES = ("method", "bank", "initial_failure_code", "initial_failure_class", "merchant_id")
CONTINUOUS_FEATURES = ("amount_paise",)
CYCLIC_FEATURES = {"hour_of_day": 24, "day_of_week": 7}
PASSTHROUGH_FEATURES = ("is_returning_customer", "customer_ltv_decile")
FEATURE_ORDER = (
    "amount_paise",
    "method",
    "bank",
    "is_returning_customer",
    "customer_ltv_decile",
    "initial_failure_code",
    "initial_failure_class",
    "hour_of_day",
    "day_of_week",
    "merchant_id",
)

# Phase 2's own default LTV decile cuts (simulator/episodes/generator.py) —
# a fixed constant list, NOT fit from data at runtime, so it is safe to
# reuse for a live customer's decile without any leakage or refitting risk.
_LTV_DECILE_CUTS = [
    5_000, 15_000, 35_000, 70_000, 120_000,
    200_000, 350_000, 600_000, 1_200_000, 999_999_999,
]


@dataclass(frozen=True)
class PropensityContext:
    """
    The ENTIRE input surface to the certified model — exactly Phase 2's
    training feature set, nothing more. No latent fields, no
    actual_recovered, no true_recovery_prob, no ground_truth_recoverable:
    those never exist on this class at all, so there is no field for a
    caller to accidentally leak through.
    """

    amount_paise: int
    method: str
    bank: str
    is_returning_customer: bool
    customer_ltv_decile: int
    initial_failure_code: str
    initial_failure_class: str
    hour_of_day: int
    day_of_week: int
    merchant_id: str


@dataclass(frozen=True)
class RecoveryPrediction:
    probability_bps: int  # integer basis points [0, 10000] — converted from
    # the model's float probability at this boundary, immediately, so no
    # raw float probability ever propagates into downstream money math
    # (services/recovery_engine/evi.py takes recovery_prob_bps as its input).
    model_name: str
    model_version: str
    feature_schema_version: str


def compute_customer_ltv_decile(lifetime_value_paise: int) -> int:
    """Map a live customer's lifetime_value_paise to the same [1..10] decile
    scale the certified model was trained on — reusing Phase 2's fixed,
    non-data-dependent cut points (not refit at runtime)."""
    return _compute_ltv_decile(lifetime_value_paise, _LTV_DECILE_CUTS)


def build_propensity_context(
    *,
    amount_paise: int,
    method: str,
    bank: str | None,
    is_returning_customer: bool,
    lifetime_value_paise: int,
    initial_failure_code: str | None,
    initial_failure_class: str | None,
    created_at: datetime,
    merchant_id: str,
) -> PropensityContext:
    """
    Build the model's input context from already-fetched payment/customer
    fields (the caller does any DB I/O — see
    services/recovery_engine/orchestrator.py — this function itself performs
    none). Fails loudly (ValueError) if a required feature is missing,
    rather than silently substituting a default that would silently shift
    the model's input distribution away from what it was trained on.
    """
    missing = [
        name
        for name, value in (
            ("bank", bank),
            ("initial_failure_code", initial_failure_code),
            ("initial_failure_class", initial_failure_class),
        )
        if not value
    ]
    if missing:
        raise ValueError(
            f"Cannot build a PropensityContext — required feature(s) missing: {missing}. "
            f"The certified Phase 2 model was trained with these always populated; "
            f"scoring a payment without them would silently be out-of-distribution."
        )

    return PropensityContext(
        amount_paise=amount_paise,
        method=method,
        bank=bank,
        is_returning_customer=is_returning_customer,
        customer_ltv_decile=compute_customer_ltv_decile(lifetime_value_paise),
        initial_failure_code=initial_failure_code,
        initial_failure_class=initial_failure_class,
        hour_of_day=created_at.hour,
        day_of_week=created_at.weekday(),
        merchant_id=merchant_id,
    )


_load_lock = threading.Lock()
_lr_model = None
_transformer = None


def _load_artifacts():
    """Load the frozen LR model + frozen FeatureTransformer from disk
    exactly once per process (double-checked locking) — never re-read per
    request, never refit."""
    global _lr_model, _transformer
    if _lr_model is not None and _transformer is not None:
        return _lr_model, _transformer
    with _load_lock:
        if _lr_model is None or _transformer is None:
            if not MODEL_ARTIFACT_PATH.exists():
                raise FileNotFoundError(
                    f"Certified model artifact not found at {MODEL_ARTIFACT_PATH}. "
                    f"Phase 2 (models/recovery/train.py) must be run once to produce it — "
                    f"this adapter never trains a model itself."
                )
            if not TRANSFORMER_ARTIFACT_PATH.exists():
                raise FileNotFoundError(
                    f"Frozen feature transformer not found at {TRANSFORMER_ARTIFACT_PATH}."
                )
            with open(MODEL_ARTIFACT_PATH, "rb") as f:
                _lr_model = pickle.load(f)
            # models/recovery/features.py:FeatureTransformer.load() would
            # re-import that module; loading the pickle directly here keeps
            # this adapter's only dependency on models/recovery/ being the
            # artifact files themselves, not their training-time code.
            with open(TRANSFORMER_ARTIFACT_PATH, "rb") as f:
                _transformer = pickle.load(f)
    return _lr_model, _transformer


def _context_to_transformer_frame(context: PropensityContext) -> pd.DataFrame:
    row = {field: getattr(context, field) for field in FEATURE_ORDER}
    return pd.DataFrame([row])


def predict_recovery_probability(context: PropensityContext) -> RecoveryPrediction:
    """
    P(actual_recovered | visible features), from the certified Phase 2
    logistic regression (see module docstring for why LR, not LightGBM, is
    correct here). Pure inference — no fitting, no DB/network I/O, no
    latent fields anywhere on `context` for there to be a leak of.

    This is a PREDICTION, not a decision: it does not choose RETRY_NOW or
    any other action. services/recovery_engine/evi.py and
    next_best_action.py convert this probability into economics and an
    action; policy_engine gates the result. Do not shortcut that pipeline
    by treating this probability as the final answer.
    """
    lr_model, transformer = _load_artifacts()

    df = _context_to_transformer_frame(context)
    x_transformed = transformer.transform(df)
    proba = float(lr_model.predict_proba(x_transformed)[0, 1])
    probability_bps = max(0, min(10_000, int(round(proba * 10_000))))

    return RecoveryPrediction(
        probability_bps=probability_bps,
        model_name=MODEL_NAME,
        model_version=MODEL_VERSION,
        feature_schema_version=FEATURE_SCHEMA_VERSION,
    )
