"""
Minimal baseline strategy for TRD §2's recovery_ledger.baseline_outcome —
NOT Phase 8's full BaselineSimulator/evaluation harness (TRD §7), which
runs many strategies across many experiments. This is the smallest thing
that makes recovery_ledger's baseline_outcome column real for a payment
processed through THIS pipeline, using the SAME heuristic Phase 2's own
certificate.py already established as "the baseline to beat": retry
everything except failures already known to be hopeless.

Ground truth dependency: this reads simulator_latent_state.true_recovery_prob_bps
(app_role — NOT diagnoser_role/inference_role, which correctly have zero
access to it) to decide what the baseline WOULD have recovered.

CRITICAL (TRD §7): the outcome dice-roll below calls
integrations.razorpay.adapter.resolve_simulated_outcome() — the EXACT SAME
function SimulatorAdapter.retry() calls to resolve a real executed retry.
This is not an implementation detail: TRD §7's incremental-revenue number
is only a valid comparison if RecoveryOS's actual outcomes and the
baseline's counterfactual outcomes are resolved through one identical
function, not two independently-written pieces of matching math that
could silently drift apart the next time either one is touched. Do NOT
inline `random.uniform(0, 10_000) < true_recovery_prob_bps` here again —
import and call the shared resolver.

For a genuinely live (non-synthetic) payment there is no latent ground
truth to compare against — baseline_outcome stays NULL for those, which is
architecturally correct: "what would the naive strategy have recovered"
is only answerable in a simulated environment where the counterfactual
ground truth exists at all.
"""

from __future__ import annotations

import uuid

from sqlalchemy import text
from sqlalchemy.ext.asyncio import AsyncSession

from integrations.razorpay.adapter import resolve_simulated_outcome

# Baseline heuristic — matches models/recovery/certificate.py's naive
# baseline exactly: retry everything except PERMANENT failure_class or an
# INSUFFICIENT_FUNDS failure_code (both known-hopeless-to-retry cases).
BASELINE_UNRETRYABLE_FAILURE_CLASSES = frozenset({"PERMANENT"})
BASELINE_UNRETRYABLE_FAILURE_CODES = frozenset({"INSUFFICIENT_FUNDS"})

OUTCOME_RECOVERED = "RECOVERED"
OUTCOME_NOT_RECOVERED = "NOT_RECOVERED"
OUTCOME_NOT_ATTEMPTED = "NOT_ATTEMPTED"

# Fixed sentinel experiment_id for baseline runs generated by the live
# pipeline (this module) — distinct from whatever experiment_id(s) Phase
# 8's formal multi-run evaluation harness mints for its own comparisons.
PIPELINE_BASELINE_EXPERIMENT_ID = "00000000-0000-0000-0000-0000000000e8"


def _would_baseline_retry(failure_class: str | None, failure_code: str | None) -> bool:
    if failure_class in BASELINE_UNRETRYABLE_FAILURE_CLASSES:
        return False
    return failure_code not in BASELINE_UNRETRYABLE_FAILURE_CODES


async def compute_and_persist_baseline_run(session: AsyncSession, payment_id: str) -> dict | None:
    """
    Idempotent (ON CONFLICT DO NOTHING is not available here since
    baseline_runs has no unique constraint on payment_id by design — TRD §7
    allows multiple experiments per payment — so this checks for an
    existing PIPELINE_BASELINE_EXPERIMENT_ID row first). Returns
    {"outcome": str, "recovered_amount_paise": int} or None if this
    payment has no simulator ground truth to compare against.
    """
    existing = (
        (
            await session.execute(
                text(
                    "SELECT outcome, recovered_amount_paise FROM baseline_runs "
                    "WHERE payment_id = :pid AND experiment_id = :exp_id"
                ),
                {"pid": payment_id, "exp_id": PIPELINE_BASELINE_EXPERIMENT_ID},
            )
        )
        .mappings()
        .first()
    )
    if existing is not None:
        return dict(existing)

    payment_row = (
        (
            await session.execute(
                text(
                    "SELECT amount_paise, failure_class, failure_code FROM payments WHERE payment_id = :pid"
                ),
                {"pid": payment_id},
            )
        )
        .mappings()
        .first()
    )
    if payment_row is None:
        return None

    latent_row = (
        await session.execute(
            text(
                "SELECT true_recovery_prob_bps FROM simulator_latent_state "
                "WHERE payment_id = :pid ORDER BY created_at DESC LIMIT 1"
            ),
            {"pid": payment_id},
        )
    ).first()
    if latent_row is None:
        # No ground truth (a genuinely live payment) — nothing to compare
        # the baseline against. Do not fabricate a number.
        return None

    true_recovery_prob_bps = latent_row[0]
    would_retry = _would_baseline_retry(payment_row["failure_class"], payment_row["failure_code"])

    if not would_retry:
        outcome, recovered_amount_paise = OUTCOME_NOT_ATTEMPTED, 0
    else:
        succeeded = resolve_simulated_outcome(true_recovery_prob_bps)
        outcome = OUTCOME_RECOVERED if succeeded else OUTCOME_NOT_RECOVERED
        recovered_amount_paise = payment_row["amount_paise"] if succeeded else 0

    await session.execute(
        text(
            "INSERT INTO baseline_runs (run_id, experiment_id, payment_id, recovered_amount_paise, outcome) "
            "VALUES (:run_id, :exp_id, :pid, :amount, :outcome)"
        ),
        {
            "run_id": str(uuid.uuid4()),
            "exp_id": PIPELINE_BASELINE_EXPERIMENT_ID,
            "pid": payment_id,
            "amount": recovered_amount_paise,
            "outcome": outcome,
        },
    )
    await session.commit()

    return {"outcome": outcome, "recovered_amount_paise": recovered_amount_paise}
